name: Check if CLA is signed
on:
    push:
      branches: [ main ]
    pull_request:

jobs:
  cla-check:
    name: Check if CLA is signed
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v1
        with:
          accept-existing-contributors: true