# .github/workflows/notify-staging.yml
name: Notify Staging Repo

on:
  push:
    branches: [main]

jobs:
  trigger-staging-sync:
    if: ${{ github.repository == 'canonical/landscape-documentation' }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger dispatch event
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.DOCS_SYNC_TOKEN }}" \
            https://api.github.com/repos/canonical/landscape-docs-staging/dispatches \
            -d '{"event_type":"sync-public-main"}'