# .github/workflows/notify-staging.yml
name: Notify Staging Repo

on:
  push:
    branches: [main]

jobs:
  trigger-staging-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.STAGING_DEPLOY_KEY }}

      - name: Trigger dispatch event
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/canonical/landscape-docs-staging/dispatches \
            -d '{"event_type":"sync-public-main"}'
